#!/usr/bin/expect -f
scp -r ./* in4342-06@ce-eslab.ewi.tudelft.nl:/data/home/in4342-06/assignment02/dimitris

ssh in4342-06@ce-eslab.ewi.tudelft.nl /bin/bash<<'EOT'
 cd /data/home/in4342-06/assignment02/dimitris/development/pool_notify/
 bash scriptMake
 bash scriptCopy
 ls
 scp -r -P 40022 ./* root@80.112.147.22:/home/root/esLAB/dimitris/Test5


EOT